---
title: "Main Analysis"
author: "Anna Fuchs, Niklas Ippisch"
format: html
---

Preparation

```{r}
#| warning: false
#| message: false
# Loading relevant packages and data
library(readr)
library(readxl)
library(survey)
library(srvyr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(scales)
library(showtext)
library(ggrounded)
library(purrr)

font_add_google("Montserrat", "montserrat")

relevant <- read_rds(file = "data/relevant_recoded.R")
```


Figure 1

```{r}
#| error: false
#| waring: false
#| message: false
# loading external data
wid_data <- read_excel("data/WID_Data_13062025-143407.xlsx")

colnames(wid_data) <- c("percentile", "year", "FR - France", "GB - United Kingdom",
                        "AT - Austria", "BE - Belgium", "CZ - Czechia", "FI - Finland",
                        "HU - Hungary", "IS - Iceland", "PL - Poland", "PT - Portugal",
                        "SI - Slovenia")

country_colours <- c("AT - Austria" = "#332288",
                     "BE - Belgium" = "#88CCEE",
                     "CZ - Czechia" = "#6699CC",
                     "FI - Finland" = "#117733",
                     "FR - France" = "#999933",
                     "GB - United Kingdom" = "#DDCC77", 
                     "HU - Hungary" = "#CC6677",
                     "IS - Iceland" = "#AA4499",
                     "PL - Poland" = "#D55E00",
                     "PT - Portugal" = "#661100", 
                     "SI - Slovenia" = "#44AA99")

# transforming the dataset for the graph
wid_data_long <- wid_data %>%
  select(-percentile) %>%
  pivot_longer(
    cols = -year,
    names_to  = "country",
    values_to = "gini"
  )

# create the graph
wid_data_long %>%
  ggplot(aes(x = year, y = gini, colour = country)) +
  geom_smooth(method = "loess",
              se = FALSE,
              span = 0.2,
              size = 1.2) +
  scale_colour_manual(values = country_colours) +
  scale_y_continuous(limits = c(0.3, 0.55), expand = c(0,0)) +
  scale_x_continuous(limits = c(1998, 2023), expand = c(0,0)) +
  labs(
    title = NULL,
    x     = NULL,
    y     = "Gini coefficient",
    colour = NULL
  ) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor       = element_blank(),
    panel.grid.major       = element_line(colour = "grey90"),
    legend.position        = "bottom",
    plot.title             = element_text(face = "bold", hjust = 0.5)
  ) +
  theme_linedraw() +
  theme(# panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_rect(fill = 'white', colour = 'white'),
    plot.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
    legend.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
    legend.key = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
    axis.text.x = element_text(colour = "#22444b", size = 14),
    axis.text.y = element_text(colour = "#22444b", size = 14),
    axis.title.y = element_text(colour = "#22444b", size = 20),
    legend.text = element_text(colour = "#22444b", size = 14),
    legend.position = "bottom",
    legend.box = "horizontal")
```


Figure 2

```{r}
# removing NA's and applying weights
svy_dat <- relevant %>%
  filter(!is.na(w2eq13)) %>% 
  as_survey_design(weights = w2weight)

# compute weighted counts for each category of w2eq13
svy_summary <- svy_dat %>% 
  group_by(w2eq13) %>%
  summarise(
    weighted_n = survey_total(),             
    pct        = survey_mean(vartype = "ci")
  )

# preperation for the percentage plot
svy_pct <- svy_dat %>%
  group_by(w2eq13) %>%
  summarise(
    wt_n     = survey_total(vartype = "ci"),
  ) %>%
  ungroup() %>%
  mutate(
    pct      = wt_n / sum(wt_n),
    pct_low  = wt_n_low  / sum(wt_n),
    pct_upp  = wt_n_upp  / sum(wt_n)
  )

# creating the graph
ggplot(svy_pct, aes(x = w2eq13, y = pct)) +
  geom_col_rounded(fill = "#AB110F") +
  geom_text(aes(label = paste(round(pct * 100, 0), "%")), position = position_dodge(0.9),
            vjust = 2, size = 4, color = "white") +
  scale_y_continuous(labels = percent_format(accuracy = 1),
                     limits = c(0, 0.4),
                     breaks = seq(0, 0.4, by = 0.1),
                     expand = c(0,0)) +
  scale_x_continuous(
    breaks = 1:5,
    labels = c(
      "Strongly agree",
      "Agree",
      "Neither agree\nnor disagree",
      "Disagree",
      "Strongly disagree"
    )
  ) +
  labs(
    x = "",
    y     = "% of respondents"
  ) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
        plot.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
        axis.text.x = element_text(colour = "#22444b"),
        axis.text.y = element_text(colour = "#22444b"),
        axis.title.y = element_text(colour = "#22444b"))
```

Figure 3

```{r}
# change the poling of relevant variables and removing 'Other' category
relevant <- relevant |> 
  mutate(w1eq10 = 6 - w1eq10) |> 
  filter(eisced != 55)

# creating new variables and removing middle categories
relevant_noNA <- relevant %>%
  filter(w2eq13 != 3, w2eq1 != 3) %>%
  mutate(
    policy_bin = ifelse(w2eq13 %in% c(1,2), 1L, 0L),
    income_bin = ifelse(w2eq1   %in% c(4,5), 1L, 0L)
  ) %>%
  filter(!is.na(policy_bin), !is.na(income_bin))

# stating the survey design
design_m1 <- as_survey_design(relevant_noNA, weights = w2weight)

# fitting the model
model_m1 <- svyglm(policy_bin ~ income_bin + age + female + hinctnta + eisced + w1eq10 + w1eq8,
                design = design_m1,
                family = quasibinomial())

# tidying and filtering model results
tidy_model_m1 <- broom::tidy(model_m1) %>%
  filter(term %in% c("income_bin", "age", "female", "hinctnta", "eisced", "w1eq10", "w1eq8"))

results_svy_m1 <- tidy_model_m1 %>%
  transmute(
    term,
    beta = estimate,
    sd   = std.error,
    p    = p.value,
    sig  = ifelse(p < 0.05, 1L, 0L)
  )

# creating the graph
results_svy_m1 %>%
  mutate(term = forcats::fct_reorder(term, beta, .desc = FALSE)) %>%
  ggplot(aes(x = beta, y = term)) +
  geom_point(position = position_dodge(width = 0.5), size = 3, colour = "#AB110F") +
  geom_errorbarh(aes(
    xmin = beta - 1.96 * sd,
    xmax = beta + 1.96 * sd
  ), colour = "#AB110F", height = 0.3, size = 1) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(
    x = "",
    y = "",
    title = ""
  ) +
  scale_x_continuous(limits = c(-0.5, 1),
                     breaks = seq(-1, 1, by = 0.2),
                     expand = c(0,0.1)) +
  scale_y_discrete(labels = c(
    "age" = "Age \n (in years)",
    "eisced" = "Highest level of education \n (7: higher tertiary education)",
    "female" = "Female \n (1: Yes)",
    "income_bin" = "Perceived \n income inequality \n (1: Increased)",
    "w1eq10" = "Importance of hard work \n to getting ahead \n in live (5: Essential)",
    "w1eq8" = "Feelings towards \n differences in wealth \n (10: extremely angry)",
    "hinctnta" = "Income percentile \n (10: 10th percentile)"
  )) +
  theme_linedraw() +
  theme(
    panel.background = element_rect(fill = 'white', colour = 'white'),
    plot.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
    axis.text.x = element_text(colour="#22444b", size = 10),
    axis.text.y = element_text(colour="#22444b", size = 10),
    legend.position = "none")
```

Figure 4

```{r}
# stating relevant country codes
countries   <- c("AT","BE","CZ","FI","FR","GB","HU","IS","PL","PT","SI")

# removing potentially wrong data
relevant_m2 <- relevant_noNA %>%
  filter(cntry %in% countries)

# nesting by country
nested <- relevant_m2 %>%
  group_by(cntry) %>%
  nest()

# creating the study design (incl. weights) and looping through countries
results_svy_m2 <- nested %>%
  mutate(
    design = map(data,    ~ as_survey_design(.x, weights = w2weight)),
    model  = map(design,  ~ svyglm(policy_bin ~ income_bin + age + female + w1eq10 + w1eq8 + hinctnta + eisced,
                                   design = .x,
                                   family = quasibinomial())),
    # in svyglm for binomial and poisson you have to use quasibinomial() to aviod a warning about non-integer
    ## numbers of successes. The quasi version of the family objects give the same point estimates and st. errors
    tidy   = map(model,   ~ broom::tidy(.x) %>% filter(term == "income_bin"))
  ) %>%
  unnest(tidy) %>%
  transmute(
    cntry,
    beta = estimate,
    sd   = std.error,
    p    = p.value,
    sig  = ifelse(p < 0.05, 1L, 0L)
  )

# arranging the results
results_svy_m2 <- results_svy_m2 %>%
  arrange(desc(beta)) %>%
  mutate(cntry = factor(cntry, levels = cntry))

# Changing labels
country_labels <- c(
  "SI" = "SI - Slovenia *",
  "AT" = "AT - Austria",
  "IS" = "IS - Iceland",
  "FI" = "FI - Finland",
  "GB" = "GB - United Kingdom *",
  "FR" = "FR - France",
  "PL" = "PL - Poland",
  "CZ" = "CZ - Czechia",
  "BE" = "BE - Belgium",
  "HU" = "HU - Hungary",
  "PT" = "PT - Portugal"
)

# creating the graph
results_svy_m2 %>%
  ggplot(aes(x = beta, y = reorder(cntry, beta))) +
  geom_point(colour = "#AB110F", size = 3) +
  geom_errorbarh(aes(
    xmin = beta - 1.96 * sd,
    xmax = beta + 1.96 * sd
  ), height = 0.3, colour = "#AB110F", size = 1) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  labs(
    x     = "",
    y = "",
    title = ""
  ) +
  scale_x_continuous(limits = c(-4, 4),
                     breaks = seq(-4, 4, by = 1),
                     expand = c(0,0.1)) +
  scale_y_discrete(
    labels = country_labels) +
  theme_linedraw() +
  theme(
    panel.background = element_rect(fill = 'white', colour = 'white'),
    plot.background = element_rect(fill = '#FFF7F5', colour = '#FFF7F5'),
    axis.text.x = element_text(colour="#22444b"),
    axis.text.y = element_text(colour="#22444b"))
```



